version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: tail -f /dev/null

  db:
    image: postgres:15-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8085:8080

volumes:
  db:
    driver: local
